# Research Assistant Personal Shortcuts Configuration
# Edit this file to customize your frequently used searches

# Favorite searches - use with: python src/cli.py shortcut <name>
favorite_searches:
  diabetes:
    query: "diabetes management treatment"
    quality_min: 70
    after: 2020
    mode: question
    description: "High-quality diabetes management research"

  ai_diagnostics:
    query: "AI artificial intelligence diagnostic accuracy"
    type: ["systematic_review", "rct"]
    after: 2022
    show_quality: true
    description: "AI diagnostic accuracy studies"

  recent_digital:
    query: "digital health telemedicine mHealth"
    after: 2023
    mode: explore
    top_k: 20
    description: "Recent digital health innovations"

  covid:
    query: "COVID-19 pandemic"
    after: 2020
    type: ["systematic_review"]
    quality_min: 80
    description: "High-quality COVID-19 systematic reviews"

  mental_health:
    query: "depression anxiety mental health intervention"
    mode: question
    show_quality: true
    after: 2021
    description: "Mental health interventions"

# Quick filters - apply to any search
quick_filters:
  high_quality:
    quality_min: 80
    type: ["systematic_review", "rct"]

  recent:
    after: 2023

  comprehensive:
    top_k: 30
    verbose: true
    show_quality: true

# Research topics - group related searches
research_topics:
  diabetes_project:
    searches:
      - "diabetes type 2 management"
      - "diabetes digital intervention"
      - "diabetes self-monitoring"
    filters:
      after: 2020
      quality_min: 70

  ai_health:
    searches:
      - "artificial intelligence diagnosis"
      - "machine learning prognosis"
      - "deep learning medical imaging"
    filters:
      after: 2021
      type: ["systematic_review"]
