[tool.ruff]
# Target Python 3.11
target-version = "py311"

# Line length matching Black's default
line-length = 88

# Exclude directories
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "kb_data",
]

[tool.ruff.lint]
# Enable more rule sets
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort (import sorting)
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "DTZ", # flake8-datetimez
    "S",   # flake8-bandit (security)
    "SIM", # flake8-simplify
    "RUF", # Ruff-specific rules
]

# Ignore specific rules
ignore = [
    "E501",  # Line too long (handled by formatter)
    "S101",  # Use of assert (needed for tests)
    "S608",  # SQL injection (false positives)
]

[tool.ruff.lint.per-file-ignores]
# Ignore security issues in tests
"test_*.py" = ["S"]

[tool.ruff.lint.isort]
# Import sorting configuration
known-first-party = ["build_kb", "cli"]

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"

# Indent with spaces
indent-style = "space"

# Format docstrings
docstring-code-format = true